// DOM Element References
export const el = {
  // Main Views
  setupView: document.getElementById("setupView"),
  revealView: document.getElementById("revealView"),
  summaryView: document.getElementById("summaryView"),
  finalView: document.getElementById("finalView"),

  // Setup View Elements
  rolesDetails: document.getElementById("rolesDetails"),
  setupForm: document.getElementById("setupForm"),
  playerCount: document.getElementById("playerCount"),
  wolfCount: document.getElementById("wolfCount"),
  wolfHint: document.getElementById("wolfHint"),
  playerNameInput: document.getElementById("playerNameInput"),
  addPlayerBtn: document.getElementById("addPlayerBtn"),
  playerList: document.getElementById("playerList"),
  reorderHint: document.getElementById("reorderHint"),
  clearPlayersBtn: document.getElementById("clearPlayersBtn"),
  validationMessage: document.getElementById("validationMessage"),
  roleOptions: document.getElementById("roleOptions"),
  roleSummary: document.getElementById("roleSummary"),
  roleSummaryContent: document.getElementById("roleSummaryContent"),

  // Reveal View Elements
  revealBtn: document.getElementById("revealBtn"),
  hideBtn: document.getElementById("hideBtn"),
  roleCard: document.getElementById("roleCard"),
  roleImage: document.getElementById("roleImage"),
  handoffNotice: document.getElementById("handoffNotice"),
  handoffTimer: document.getElementById("handoffTimer"),
  revealStatus: document.getElementById("revealStatus"),
  roleTeam: document.getElementById("roleTeam"),
  roleName: document.getElementById("roleName"),
  roleDescription: document.getElementById("roleDescription"),
  playerProgress: document.getElementById("playerProgress"),
  currentPlayerLabel: document.getElementById("currentPlayerLabel"),

  // Summary View Elements
  summaryList: document.getElementById("summaryList"),
  livingDetails: document.getElementById("livingDetails"),
  livingCount: document.getElementById("livingCount"),
  fallenDetails: document.getElementById("fallenDetails"),
  fallenList: document.getElementById("fallenList"),
  fallenCount: document.getElementById("fallenCount"),
  mythPanel: document.getElementById("mythPanel"),
  mythStatusTag: document.getElementById("mythStatusTag"),
  mythPlayerLabel: document.getElementById("mythPlayerLabel"),
  mythInstructions: document.getElementById("mythInstructions"),
  mythTargetSelect: document.getElementById("mythTargetSelect"),
  mythConfirmBtn: document.getElementById("mythConfirmBtn"),
  mythResultMessage: document.getElementById("mythResultMessage"),
  mythSummary: document.getElementById("mythSummary"),
  mythSummaryText: document.getElementById("mythSummaryText"),
  dayCounter: document.getElementById("dayCounter"),
  nextDayBtn: document.getElementById("nextDayBtn"),
  guideProgress: document.getElementById("guideProgress"),
  guideStepText: document.getElementById("guideStepText"),
  guideFullList: document.getElementById("guideFullList"),
  guideNav: document.getElementById("guideNav"),
  toggleGuideMode: document.getElementById("toggleGuideMode"),
  prevGuideStep: document.getElementById("prevGuideStep"),
  nextGuideStep: document.getElementById("nextGuideStep"),
  eliminationSelect: document.getElementById("eliminationSelect"),
  eliminateBtn: document.getElementById("eliminateBtn"),

  // Global UI Elements
  infoFooter: document.getElementById("infoFooter"),
  restartBtn: document.getElementById("restartBtn"),
  openSummaryBtn: document.getElementById("openSummaryBtn"),
  modalOverlay: document.getElementById("modalOverlay"),
  modalTitle: document.getElementById("modalTitle"),
  modalMessage: document.getElementById("modalMessage"),
  modalCancel: document.getElementById("modalCancel"),
  modalConfirm: document.getElementById("modalConfirm"),
  languageSelect: document.getElementById("languageSelect"),
  languageToggle: document.getElementById("languageToggle"),
  languageFlag: document.getElementById("languageFlag"),
  languageMenu: document.getElementById("languageMenu"),
  languageButtons: document.querySelectorAll("[data-lang-button]"),
  languagePicker: document.querySelector(".language-picker"),
  infoButton: document.getElementById("infoButton"),
  infoOverlay: document.getElementById("infoOverlay"),
  infoClose: document.getElementById("infoClose"),
  menuBtn: document.getElementById("menuBtn"),
  mainMenu: document.getElementById("mainMenu"),
  menuVotingBtn: document.getElementById("menuVotingBtn"),
  menuImmersionBtn: document.getElementById("menuImmersionBtn"),
  votingOverlay: document.getElementById("votingOverlay"),
  votingClose: document.getElementById("votingClose"),

  // Final View Elements
  victoryTitle: document.getElementById("victoryTitle"),
  victorySubtitle: document.getElementById("victorySubtitle"),
  victoryList: document.getElementById("victoryList"),
  finalNewGameBtn: document.getElementById("finalNewGameBtn"),
};
